export const AUTH_IS_OK="AUTH_IS_OK";
export const AUTH_NOT_VALID="AUTH_NOT_VALID";

export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";
export const BACK_TO_SIGN_IN="BACK_TO_SIGN_IN";

export const ADD_NEW_WINDOW="ADD_NEW_WINDOW"
export const REMOVE_WINDOW="REMOVE_WINDOW"
export const SET_WINDOW_POSITION="SET_WINDOW_POSITION"
export const SET_ACTIVE="SET_ACTIVE"
export const MINIMIZE="MINIMIZE"
export const MAXIMIZE="MAXIMIZE"

export const SAVE_USER_SUCCESS="SAVE_USER_SUCCESS"
export const SAVE_USER_START="SAVE_USER_START"
export const SAVE_USER_FAILED="SAVE_USER_FAILED"


export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const GET_USERS_FAILED="GET_USERS_FAILED"
export const GET_USERS_START="GET_USERS_START"

